version: '2'

services:
  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    restart: always
    environment:
        - MYSQL_DATABASE=root
        - MYSQL_ROOT_PASSWORD=admin
    ports:
        - '3306:3306'

  redis:
    image: "redis:alpine"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  comas-app:
    depends_on:
      - mysql
      - zookeeper
      - kafka
    build: /kafka-docker-spring_boot-base
#    keep open the terminal after building container
    stdin_open: true
    tty: true